#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: gateway
#  namespace: sock-shop
#  annotations:
#    kubernetes.io/ingress.class: "istio"
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /front-end
#            pathType: Exact
#            backend:
#              service:
#                name: front-end
#                port:
#                  number: 8079