apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sock-shop-infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/Siar-Akbayin/sock-shop-infrastructure
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: sock-shop
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  dependsOn:
#    - name: istio-system
#      namespace: flux-system
#  sourceRef:
#    kind: GitRepository
#    name: sock-shop-infrastructure
#  path: ./kubernetes/flagger/canaries
#  prune: true
#  validation: client
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: receiver
#  namespace: flux-system
#
#spec:
#  type: LoadBalancer
#  selector:
#    app: notification-controller
#  ports:
#    - name: http
#      port: 80
#      protocol: TCP
#      targetPort: 9900
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: flux-system
  namespace: flux-system
spec:
  events:
    - ping
    - push
  resources:
    - kind: GitRepository
      name: flux-system
  secretRef:
    name: webhook-token
  type: github
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: notification-provider
  namespace: flux-system
spec:
  channel: flux-notifications
  secretRef:
    name: discord-url
  type: discord
  username: flux-bot
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: notification-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: ImageRepository
      name: "*"
    - kind: ImagePolicy
      name: "*"
    - kind: ImageUpdateAutomation
      name: "*"
  providerRef:
    name: notification-provider
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  timeout: 1h
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/istio/operator
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istio-operator
      namespace: istio-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-operator
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/istio/system
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: flagger
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: kiali
      namespace: istio-system
    - apiVersion: apps/v1
      kind: Deployment
      name: istio-ingressgateway
      namespace: istio-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: istio-system
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/istio/gateway
  prune: true
  targetNamespace: istio-system
  validation: client
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-bot
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Siar-Akbayin/sock-shop-infrastructure
  ref:
    branch: master
  secretRef:
    name: github-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-bot
    namespace: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: front-end
  namespace: flux-system
spec:
  secretRef:
    name: gcr-json-key
  image: europe-west3-docker.pkg.dev/privacy-with-canary/sock-shop/front-end
  interval: 12m
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: front-end
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: front-end
  policy:
    semver:
      range: ">=1.0.0 <2.0.0"