#apiVersion: v1
#kind: Service
#metadata:
#  name: front-end
#  namespace: sock-shop
#  labels:
#    app: front-end
#    service: front-end
#spec:
#  ports:
#  - port: 8079
#    name: http
#  selector:
#    app: front-end
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: sock-shop-front-end
#  labels:
#    account: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
      annotations:
        sidecar.istio.io/extraStatTags: destination_port,request_host,my_request_id,gcp_location,destination_address,my_method
    spec:
      containers:
      - name: front-end
        image: europe-west3-docker.pkg.dev/privacy-with-canary/sock-shop/front-end:1.0.3 # {"$imagepolicy": "flux-system:front-end"}
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 30
          periodSeconds: 3
      nodeSelector:
        kubernetes.io/os: linux
