apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: front-end
  namespace: flux-system
spec:
  secretRef:
    name: gcr-json-key
  image: europe-west3-docker.pkg.dev/privacy-with-canary/sock-shop/front-end
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: front-end
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: front-end
  policy:
    semver:
      range: ">=1.0.0 <2.0.0"