apiVersion: v1
data:
    password: ENC[AES256_GCM,data:sEvaywyQ6MC+izCJ,iv:atID6MmUlW58XDY1mouYuHJUBfpAv5WXRya9g1JNlss=,tag:hd29whqTeYF2UAntjAU/7w==,type:str]
    user: ENC[AES256_GCM,data:SAcr+SA9b+U=,iv:1P7NpPByf5/0fEkQtsQW8Ujxg1FuubLZWUbMFp+q/0c=,tag:wV5P0MssEbpJ/VIPdChkqg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-01T23:08:11Z"
    mac: ENC[AES256_GCM,data:PMT2ex1ZG8T9IKUysvb2rVezCOdPg0iPaPtaqsSONsQeip0TThryBaMST6RiGG4tXn9xHA5WAGxb4Wc2Git24IEPqS/xyuWE6/ehnhb0267qjos8970xYZuc9Or2TmhUOMV1M5ey5LYgb2n733kgknhXIZoWQjOWt3BLEceqAxE=,iv:3CMC3yqCLbp1VtKI5cfC9+E+9D3vTA2HvccAq5kiKmQ=,tag:V494ROzlU4HKRCEy5v+Kwg==,type:str]
    pgp:
        - created_at: "2022-12-01T23:08:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5UzGPk9UqCNARAAmHWRyBrEbJkp6Ux4b1AdUGB7AIwwE1JMQ0vIr3WHppyp
            XUMKVKb06jg9tPRV2pLfxU7dOW2xWAzYy42tV+yzQwN3fn0/ls1AzbxVPZfVlla2
            vo1kaqahAgUfgEr4+/XLMq21FEfcP7Azj3rtRc2fv1iAeoBjhQfr8KxwitTwfnAV
            I5ewo0SICNe2cgYZRtRD4A/z9EQS/02s6NlGo3x3WS1Qsw61eW31cvLSs0lWTu9I
            Sm5e8teXLUvjuRnIMqIcoLGBUj7bZN0bnbt5s58atnEBAVYnQHtF4NT8Kq1Lo/sk
            AO79vRiv3aMe9vHCw7xtNijNiT6JFDhf4175NPZhXFTwrkf6kf5YcpdRYCUpvLun
            hnys/PvjpaPCcWRoXomZAhavLMsnsW3a6mfq7eEh3nObP9jySvaqAM05FsTxzMl5
            cDuagPVb9GXHdMLyzE8/oon0aKRYldqCoDe45GA0a9Ikc9nFaD4gmBld7xr3hkJF
            aPojxTb8CExh884QTpQ/KSc4cYWO45dx78oa1EMG6Le5YcVERzauEcdZZgxGn4ke
            X1XbiOr2nlXy4YFy7m9Ic7xx9ULguuZ9bpRmJMGyj1oe000/MINLfdpr2w9b41Fv
            ctj1H0SSoExQleeBHUd8tJWePBckb5NAbIeR5pa99Mjm0mha1qJ3Y5VX019HvgzU
            aAEJAhD/fLKxfi4DS93XwexxmpFeMYwTQ8572lUTs7wR6DekA1NVd7wd4qgOswM4
            wkdGU9J5eCXL/RsfRGuR8DDchftZz91YsZdKKIIfWhDd2USXz1R7l8PbFnjsjAxv
            dkQvpp6FtEnU
            =47zm
            -----END PGP MESSAGE-----
          fp: 83B4048A17C5AA4A424588042D2238C5A65CEB2E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
