apiVersion: v1
data:
    password: ENC[AES256_GCM,data:yHSMKc4HbzbjFrFI,iv:lJaPs/Gss6GhSJF1EPuNCexKI5Qm2exH9bf1ZBJyOIY=,tag:4yeIq9nb7s0h74Qr9BUwSA==,type:str]
    user: ENC[AES256_GCM,data:bdmKOst1sZ8=,iv:d/Q+7HPnqWaK922tl8k4fa0bnB7uSzQrBrwxSR4Xw2A=,tag:OnoFo2d7QEJepnBEOlw1LA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-30T00:22:55Z"
    mac: ENC[AES256_GCM,data:bLF/6xw4eIP3JEZpx33ILX60c0EJX1adWYNgF4v3rKeJErGI+nVweM2ZejfKWmeFaTis6jgOBgJj5n7iB7CwMOxIAcraTcXs5JoMI7oZEjR27gL1huLAsSgmb3pRz7lcmTPa2+tvbWIaLenG8PotC8V30BLOJLO6KixlNEh0nUg=,iv:9Oz7J6LShQYsK4T44a4l6E+AXOZ0OsoIRRUp+YJlumM=,tag:NBQhLf3Jc+ufqUxELP6XNg==,type:str]
    pgp:
        - created_at: "2022-11-30T00:22:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4H+Sri7Y3mrAQ/8CsQH5JMbiD+im/nyDC3Dfk0B48bdRE4d2IbLSpbIjmZ1
            Ytx/1aiYpx4TaLhTdUYeYRlVSrk2QcHaPcRcCWZny8lrhAiec5FQB/d75rop/vs2
            O+XRe+sO5hjazDEn0YnlXWyDCFMEno2m3iC/RqPdVgpSMZmmkRjawkfXZJPNuVc1
            Y58br2DCOhV7jLkIzEG39jGr6uozrm6YpMrDQd7/BxgXU/vRlTDgGX14QMOyKFhU
            NX5DsKzh+34KtiE5IXVjsc/QEbd4PXhb/LmQX0ZZVlwFynEDAffAgrD/T4pSTmUd
            icaIEN/n+ydwcy7PHhU4zBoDTjonwevPd7hYXV/25bI37WOYFPguX3tGfDQnAzFT
            Ow2J044a8Vfkwiz2jkredmbi40r4EaAkrSJ6VOwevrjdQc4RppSi5DH0JKJqScRj
            ZuttUAmce9oJyG40l5DkS1rZpu9ehXy1Yeg2Gz4KpEpZJGTU5Csd77SgNYo6xRf6
            AsA7WxxqvAEPAhCWozOv2ZQhZrb9AKWpGdxnJtbNHLOV7jlm3dhvP3uDr5zyIzNs
            Ahmg36kAgHWh0j9a07GkF4o8oSW7CTQhmctheleouBVaV5nJeB542M4pzvfjk/JB
            SO+k3tq0PNRmMDVwLSHbmio3FJuBPKFcTsljNjQ77T5gYLokndUpIV8qqPJFMKvU
            aAEJAhDwdlq9O3LvRTY2RcE9Cenjn9LL5eE13pVF444n9sfG/0Xc3SNrn2iMPSL7
            iSVjdlS133vVKLLnSbNFwyIM43yjXcAzyyGtPmtzP6vcYMfgwvAXsdyFa5KmwNjh
            AY4km47P0GMx
            =hluP
            -----END PGP MESSAGE-----
          fp: 55F938D66067C0FE7AD1A1E0493C0727DC4A940C
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
