apiVersion: v1
kind: Secret
metadata:
    name: discord-flagger-webhook
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:xIM+ugFkuLf0J/nq0ayfIOAbEbYNl2wKNDcINrmZEEXi/mWg9b/XnQCxwNCMR3oRdNu37DbGc3Yka9dtUlwtVefe6jtH5RmISFwlEpcCyjr7NrjkeDL4fN1Wm4dfUwcLV+hSXsrZ01Rw9N9C8z2X/QNaVRGwIfn8,iv:ZNXMwKSpU9ZAkHSxYMaCJVO66UcQNkN1fu+zJbI1tJQ=,tag:ebV5/nYryVAVS3K08wbUsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-13T09:44:03Z"
    mac: ENC[AES256_GCM,data:zU+bDoFLKBBxtfIjGRDWX4zBHg8cnZQzhItw9W3y1PyibWMpr+Ddcf+2N/WHhmZ83dvNXK4X7waY/2ReP8XAFtNemXaEJ7LOoDqKnXNK7GIZHoJIsxMqcjyDuauwYpiBr7woQjsLbc7xWVEFYJF4brAJ+7bSEcqziZDUpYLR/I0=,iv:HUEuoaV589xgPRrPvDK9CYCaaD1hn3z1aOJisJxmKMU=,tag:+b5kTIGoUOgA7hziG+aqjg==,type:str]
    pgp:
        - created_at: "2022-12-13T09:44:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5UzGPk9UqCNAQ/+IQOjfFMYGwdINd59Z4aPjJ7MAa25jup7o73Zt9rPpJqZ
            CDjwFkKjpD0+bBDFEk/bCaIMQyUKr68w33p75xxAOZPUunYW6/NwXuGm4915hkBG
            twzrPSbtXrJaT3Vvu4oAfjFGNSJAmH36U6gORatPJTMs28hdvSL1eFDz6IAEUIJR
            s9ZKFsXgBqOTcrUX2ucThhLcpawQ3W8d1Cqx8DSG/yOEJHtCptQKgJyiVzHgKAmP
            QKBKMC3lsgi7jaSZMLjZLqz7wtSY1F8n/D+auMBqwKYDrooUPvs5oAcu0lKFwPw5
            UhCfz+95b0smfLb29eaoVg8pUr+qklVph5RftqvxvBEI978vdpI003TJ6jRmD8hU
            Pa8P4Itx2NOp2QJk2oroiTcAHU4pHn48kVVlp81bAJ7JKOUDe1oBpvigS4TE84sc
            SxbU+w7EKKxIUvhftWjYxGvtaraL2jb1J1qwU8xVzAhgKCt98CKLk0mu6jeUSY8y
            +nIrBWdRsYUc/7xgprGtK2IYFtJ+wqe/yx3tFJMvECusIsegrOmZcnPa6zCtg10N
            3j0RxB9i0sKB2Cnjtj3fTMzzzeEO8yYPY0ic/d8+83fLn2Z6DDea0Yi0MnFn7W0O
            hmDeZiPRB/ltPd4h9nX29/HXNG0y6R+2+xDyZHfOrFIsHpVPIq5BhJXPiHit+VnU
            ZgEJAhAc2xrInuhir9V14jEb3CyIWyWIjFT0CtQSGfkiq/KXAIyNA+RITPn3kq8x
            xcw6r26tz8tuSaixvtgc7BuMnkI9IIHJEMaY7K619XC3qXjxb5fv2QgjGhaWgHAW
            Mapil6GeDA==
            =G/jQ
            -----END PGP MESSAGE-----
          fp: 83B4048A17C5AA4A424588042D2238C5A65CEB2E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
