apiVersion: v1
kind: Secret
metadata:
    name: discord-flagger-webhook
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:b8cLs4025GjH+H9zxTL4IgDbtnxYugguOQsgQYC2fnjCTpjVkl/YSdBKRvAiZy/WajM5bQSpCSO1+Mt2t6He00pqYnaiQzaaj0ROIcL+hZUzWcmapvmCS+ikrhLaYMRvk+wL9O4fAQfdmfWoMa0/ZiZ3ay2LjFMwpHVaDUXXqMolNq6KWztAwLt43+b4niSKi1V5tS5aSCL5iJ7SVvKpaw==,iv:iKbnlHq28V/ZzGG8HdV3vpbn1c20Ro5yrV3ufrs0BjU=,tag:enrsNgUgDmA/BZ5p2SS1fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-13T08:41:39Z"
    mac: ENC[AES256_GCM,data:yhgFJWnHqUFzKfecIE7Y04TpxLIa6lzu+3BsFQnkrVoyPzG9LFv9McZcPKP4f1BJhMZmnf+MW4NXyatdRd0khSJnPcjXA9uwzHZzxumHgC2bQ7jM1/6Qu4XQ5YUI1B+NnUpWBzY24mJZ8/ZqeyZMJO7LOlL32bbEPO63r+rLEPY=,iv:YZgYMkOzNeSra8hGA7NFOuXX6TPhV9y2QyKdj7Sh2Mk=,tag:pwqoMZ6kZaajbdlKiKV+Fg==,type:str]
    pgp:
        - created_at: "2022-12-13T08:41:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5UzGPk9UqCNAQ//ZPkujaRZyIR69Utc9o4YeZCzhD+n8PegxAiIHVTjG/Xg
            1lkc08J8F9aQZCqMYvmXteJCcfHXPm1bIW64LqK78cWhIV/CBhJjayEs5vL0eMAB
            sj6TLzdBoTAMBrpl0mGcm95I7KIJvcFLvYMxdLyuhCndKbFuk/UxBd+IE0v1p1JX
            Yv4YoWkLEcHzwDVX+C5EtWXJew5jYnhvrvzrYO3tIxoL+0SxYeHNjC3BApqqzMU9
            c2dJJ/DtHRYMwR2XPKyTS4bgdYSVwOqYM0NFtXfvUoZaHxv4eOFErfYpsOmoAxNQ
            SeAyN2vUqkLBEbRaGEW16267V1rNMsSGz9Wv2KPfp3Cyw8X04odJ5tOTQbHmjYS3
            AtY0ZXNf0kdYXvj+UZXNhGLE9KHrx/foFSdc2jKlbHGTFgOug7q4vv4j+QgUDu6G
            ewKJTW3qrasQH4cMc8TNyDnXrLvRMTI3GeHH4rGWVQpLzOUGs57mV7muNqpjP9oZ
            fF/PiIA4VXdKQy2sFz8CBNsNRAzY7fouEnmu/IrEc1LJ/e+iIpc3qIXvCFvzooeC
            8LpNsi1JktoQH3lIx1HauYe1rC0wiBjsDbbNfpW5zcnA/4TbQdx0iUQ7BHmO/4+5
            Ouhtp5Z3l6Botq5JpUl1WeLuawViFcYL381pZX5XVC7cOPimpoSOL8DD+H8V9e3U
            aAEJAhCvFPn8mAy5xqMhmS5MfsUhMF30pUD9jz55kjT0W9SQ54N7icjG1oXCaRse
            GDsn0fnIR1s2EDB2ETrGzXCNueL59btHPThFr7bnHcIvX+blZgkBzifbWn12Q/Td
            7aSzXrhU3q3d
            =YfXU
            -----END PGP MESSAGE-----
          fp: 83B4048A17C5AA4A424588042D2238C5A65CEB2E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
