apiVersion: v1
data:
    password: ENC[AES256_GCM,data:otq7PfSUsgvmBXqHHU+Ktu0tGWoMuQSyz9Ddz3DnOT2OZ9b7VJr5WbyOqSlmO+Da4rgb0xzZOWo=,iv:V1W8tO/ash8mpaoLqZb8OFUDyGLJvzmr30UX2IeT2R4=,tag:5GGT4H+ixnF3w/n21W4o8A==,type:str]
    username: ENC[AES256_GCM,data:xghjdPc7kZzAXGjdvXT6Qg==,iv:WyWC6i8XAeyAsLYbJ66JFdbsSjKMMU+UYKxA9O9ENYk=,tag:mm4czox4oyecuwo6KXsjvg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-credentials
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-12T00:39:46Z"
    mac: ENC[AES256_GCM,data:Kx26n7UITxVU5FRiPLA2nHkstxGXb+If92xyHxot/o/ZhA7FJcsxmqji0s5KOHPUJpm9ELECrqygNFXiEeWSOXY3BUDxT+eiGXKVUUnf2kUGI6yFALe21NgIxGD2S8Tv7lU9WUaanDz68hjCXw8UAahSAxJAADAv5e/SxQcZbZQ=,iv:ZvVfGdxYb88UE5tcm8ni8U2mcpp8AZMRPhjkK0vxGXI=,tag:BajcOibuVKnF7cEgRiMhVA==,type:str]
    pgp:
        - created_at: "2022-12-12T00:39:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5UzGPk9UqCNARAAjs9Z/rlJLkHwQLUyN+9URFBefInOE94yCfVSbMmy0tWy
            CJ1HL72yQR7Q//2a2Z6qISidbZwmY7rqM4tbU61EfUuUL8Dktsih0P7DB6cL/1E9
            LGo3wJ4kSlcKCPuY9awRvE07GEjMo8WGkIcaCe1eOBD4b/66wGA2Z4WnbgvvxAVw
            jaa9VAPZ0rSQprOZGRUM0idVNGF0HfSCFz3STCuGSVwc9tkfABoBwic8KUGZzFvu
            lKnuuor+HQqYRO00sJGWQjOiVcNMPtSOpYLaz1FDkRqhUrnwLxY6QAZt6yLp6jKl
            sYUglCOb3cqm8WKv1LO3mY3TNNYlCWOsan40CjbF+ikE8h8umwafJrclIjPXGhkL
            DkfneXPhLo2Fv5enNeS9upaWREaOL0PytsazlWnOSaQiVfCeTc55iKaZxM5rO28B
            j0AfcbAb/exZv/wKdsCaFBsDYGTbGBM/a4dHy/ejX/KfAiAI9JwPpjorOl69tV8d
            evTg2pUpJNLj3cqFTvodo2UfKjEGt4Ns1oIaQt49UKdxCle2UeH+GupGTXve/z/d
            M97e1rIzvkixCaiViBCS6xElrjmk6BBncCZS1O34o2GtoIjEf2VyC0YWIfCNaMN7
            R4ji3B1aJHlHy9yQDH2/g/bh7RmiduxAFzlKAYNr7qGIy97ZG9zse4gth5Vg2gjU
            aAEJAhC8zOFs2qI/+L/H+Y3NqIAfSAb1lESoOcN/j3sFdr++FZhVmD93D4Px/87V
            HarxK2PbMqBiF1ndrWwUdlIaA8RsAc3YF8/JjZEmZ0qCUwba9fgSeVTxNU8UTLnX
            nsJpYJRrHsD5
            =HRB+
            -----END PGP MESSAGE-----
          fp: 83B4048A17C5AA4A424588042D2238C5A65CEB2E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
