apiVersion: v1
data:
    password: ENC[AES256_GCM,data:XIw+gXNiYsvdgve0KIsnCe93loye4bw5ZPw2jsHIYg5311RlUDFz+L4oTQdpuQ+8OJtGtqiVunM=,iv://D/3jCspQJ8WnbEv4en/aCfO++X4ib4IitzbKRFyA4=,tag:40xfYdH3anRkiMJrq8XRHw==,type:str]
    username: ENC[AES256_GCM,data:Zwkz+gKDO9cuaMz9hlcD+w==,iv:EymHWXRjqByHMb/qeoLvf1KTsVJR7vjYKw/GD2QpRAU=,tag:eZosSaSxQNa3RHDIT9O2MA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: github-credentials
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-01T23:30:44Z"
    mac: ENC[AES256_GCM,data:enZ76qazvuNDKfaVbrSryMrS2r6DPYcuXfqi5dgIiBSLXfyBgnaxS3XNtqjiWSku6LhVlnTYjeS6aM6r+V9Y8elOYrfsNbqqgbTJ8l5JCi4MDxLzIUsg6titxWaNhbRA5Oi2Ahj2zUnXZxAEYcm01Wht9qSYP3h5Q5cZfKBB9IM=,iv:ZVFYHUrcDgpB179U/rlabBNIT9tXYuRyRdhq+XnYPx0=,tag:dXtmfATrBxku8X3VUEBinw==,type:str]
    pgp:
        - created_at: "2022-12-01T23:30:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5UzGPk9UqCNARAAj8Kq8vPB1MTOf6UYmB+rekJcCLAL0Wduut37vz27VeQB
            Gxb0jLLR30iIR3bSLe2auROg+DQ4305G0efIED3/Yf3qyMJSggxvZhW+KpgkIL/v
            jmtsqsf05bAHYQALERNwEWeUdTW8MHyAhSfFTHN/mDBEAeMkH6rQNfZxqsNxQ4KP
            bCCSEAHsyLVku4UGPwzveNt5GsgsePJt+O+Ya+KRun4/kxe/12+oaiWOMVCsr7Qg
            gcEA9GNzeFFh1XKDsRBayJATJkxxjLi8DTIoZ8CtsGFWLKjL7dc0c+IdkPRyhnUj
            NzcUEDvsLWMb4AlCF1foHYJzD3lIxQHcc7rlz2VXXWvoLrJ+ls22cGk6DKuui9pC
            SYdAbLKzCZKknN2C6AcAww+8jvAahacJ2i8olu2FdIm/lItomyBtVMtnog5DFrZQ
            UwJG3HbnqCRYOyQCj9NsXjs7FQx7PLANuU2WiWh4kgaGcGuujtBkcgmTqUPfHJ0O
            DtagwWUcsBrKnsE2xbHuAwqAvOFi6O8jXP1DkncZ2a9M4yhLcjDOEgws2G9ewnyo
            n6pJpQ9cDU9CtGdjiRjR1s+1jJ9A74Fz2PZ6ioUAjykvtxzBwqkRJ7Pg124JjGHh
            4Y4MfRtsEgtrEHyDVxin1HQTs12tT7/Y0jdF54VEksD4xfN09pgT0casGlcipeHU
            aAEJAhCw3Mfw54rUM5hLe54CSBaczokY34A6nJwA1atpcFRnMxxtH+3m2qVmmF08
            1did58wqI58TQcLnbRCcBoQoNt6XlnEkH7YAL40mwwhCG3u4KZ1mpjlqpyqeaFnI
            zF3OTc67JeHv
            =kFxE
            -----END PGP MESSAGE-----
          fp: 83B4048A17C5AA4A424588042D2238C5A65CEB2E
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
