apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Siar-Akbayin/sock-shop-infrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: my-secrets
  path: ./secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-bot
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Siar-Akbayin/sock-shop-infrastructure
  ref:
    branch: master
  secretRef:
    name: github-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-bot
    namespace: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: front-end
  namespace: flux-system
spec:
  secretRef:
    name: gcr-json-key
  image: europe-west3-docker.pkg.dev/privacy-with-canary/sock-shop/front-end
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: front-end
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: front-end
  policy:
    semver:
      range: ">=1.0.0 <2.0.0"